"""Enhanced user and chat models for educational context

Revision ID: da6565530b78
Revises: a05a771d7617
Create Date: 2025-05-15 23:58:24.539791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6565530b78'
down_revision = 'a05a771d7617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_area', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('concepts_covered', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_grade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('school_board', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subjects_of_interest', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('learning_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('field_of_work', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active')
        batch_op.drop_column('field_of_work')
        batch_op.drop_column('learning_style')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('subjects_of_interest')
        batch_op.drop_column('school_board')
        batch_op.drop_column('current_grade')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('concepts_covered')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('subject_area')

    # ### end Alembic commands ###
